name: Multible jobs
on: push
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: install Gowsy prog
              run: sudo apt-get install cowsay y
            - name: excute cowsay CMD  
              run: cowsay -f dragon "Run for cover, iam dragon ...." >> dragon.txt
            
             - name: upload artifact  
               uses: actions/upload-artifact@v3
               with:
                  name:dragon-file
                  path:dragon.txt
    test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps: 
        - name: Download artifact  
               uses: actions/download-artifact@v3
               with:
                  name:dragon-file
        - name: test fille 
          run: grep -i "dragon" dragon.txt
          
              